### ISSUE TITLE
How to I actually use this repo?

### ISSUE THREAD

**Issue by Swagnoor19** [opt-nc/yamlfixer#3]
So I tried to clone this repo and run the yamlfixer command in the folder, but I'm getting a `command not found` error. Is there another way to install it? Thanks!

**Comment by tamere-allo-peter** [comment]
Hello.

You have to ensure that _yamlfixer_ is `chmod 0755` and that you either place the _yamlfixer_ script in a directory present in your _$PATH_, or that you specify the directory when executing it, e.g. `./yamlfixer ...`

Also ensure that https://github.com/adrienverge/yamllint is installed on your system, because _yamlfixer_ needs it and expects it to be present in your _$PATH_.

Other than that _yamlfixer_ is autonomous and only uses Python's standard library, you can move it anywhere you want.

Hoping this helps.

**Comment by Swagnoor19** [comment]
Thanks for your response. I changed the permissions for the yamlfixer file, added its path as a $PATH variable, also made sure there was a $PATH variable for yamllint. I also have python and python3 installed. Now when I run ./yamlfixer in its folder or if I run ./yamlfixer /path/to/folder, nothing happens. The command line cursor just keeps blinking.

I'm including screenshots of the variables and permissions.
<img width="256" alt="Screen Shot 2021-12-14 at 11 05 43 AM" src="https://user-images.githubusercontent.com/38535944/146035544-82c7fa95-dd06-4698-b9ff-2d925a437e19.png">
<img width="282" alt="Screen Shot 2021-12-14 at 11 07 21 AM" src="https://user-images.githubusercontent.com/38535944/146035623-22193fe0-81ae-4624-9331-536f29be57e4.png">

**Comment by tamere-allo-peter** [comment]
_yamlfixer_ currently doesn't support directory names as its arguments, you have to specify YAML file names instead, like 

```
yamlfixer --debug --verbose --backup /path/to/folder/*.yml
```

Sorry for the inconvenience.

**Comment by adriens** [comment]
Hi @Swagnoor19 , please take a look at the dedicated [Katacoda scenario](https://www.katacoda.com/opt-labs/courses/devops-tools/yamlfixer) and let us know if it matches your answers.

If it does not, please drop dedicated issues so we can get a chance to embed answers into the Katacoda scenario.

Thanks again for your feedback and interest on this project that helps us making it better.

Also, be aware that you can very easily install `yamlfixer` with Docker on Linux : 

```shell
alias yamlfixer="docker run --rm optnc/yamlfixer  yamlfixer"
yamlfixer --version
```
