### ISSUE TITLE
Yamlfixer doesn't detect alignment issue

### ISSUE THREAD

**Issue by mbarre** [opt-nc/yamlfixer#9]
Hello @tamere-allo-peter ,

I used yamlfixer on a github workflow file and the tool doesn't detect an alignment issue whereas yamllint "does".

I use yamlfixer throught [yamlfixer-action](https://github.com/opt-nc/yamlfixer-action) that regenerate a pull request with changes done by yamlfixer.

You can see the changes, it proposes :

![image](https://user-images.githubusercontent.com/1823161/156942644-917cce05-e5a0-4f01-9f53-c0e018a3cff8.png)

There's no changes for line 20, whereas yamlint gives :
```shell
❯ yamllint .github/workflows/build_hello.yml
.github/workflows/build_hello.yml
  1:1       error    too many blank lines (1 > 0)  (empty-lines)
  2:1       warning  missing document start "---"  (document-start)
  22:1      error    too many blank lines (2 > 0)  (empty-lines)
  20:14     error    syntax error: mapping values are not allowed here (syntax)
```

Could you do something or not ?
Let me know if you need more info.

Thanks in advance

**Comment by tamere-allo-peter** [comment]
Unfortunately, this is a behavior to be expected : yamlfixer doesn't  care at all about YAML syntax per se, it works by acting on explicit (like "too many blank lines (2 > 0)") hints given to it from yamllint's output. On line 20 there's no explicit hint, which could be for example "mapping values should begin on column X". I'll try to do something about it though, but I must think a bit about the best way to do this. Please @mbarre could you provide a link to the faulty YAML code so that I can do some testing, much difficult with only the screenshot ;)

**Comment by mbarre** [comment]
Yes, I saw  this message was not really explicit...
Thanks for trying anyway :)

The real file is here :
https://github.com/opt-nc/demo-yamlfixer-action/blob/main/.github/workflows/build_hello.yml

**Comment by tamere-allo-peter** [comment]
Thx. I'll work on this ASAP
